### ISSUE TITLE
Your stuff is broken

### ISSUE THREAD

**Issue by wwat** [romainr/hadoop-tutorials-examples#1]

**Comment by enricoberti** [comment]
No need to be rude, @wwat 
For a change, instead of just pointing fingers and saying that stuff doesn't work, why don't you give back to the open source community and try to fix it or be of help?
Thanks anyways for the heads up, we are having a look.

**Comment by enricoberti** [comment]
Before we come up with the pom fix, you should try what's specified on the README, like

javac -cp "/usr/lib/hive/lib/hive-exec.jar:/usr/lib/hadoop/hadoop-common.jar" org/hue/udf/MyUpper.java
jar cf wwatdh.jar org/hue/udf/MyUpper.class

**Comment by wwat** [comment]
@enricoberti What makes you think I didn't contribute anything to open-source? 

And, yes, there is a need. If you put stuff on the Internet and it doesn't work, all you are doing is wasting someone's time (in this case *mine*). 

I already have written my own Hive UDF now, which *does* actually work and it doesn't depend on your stuff. You get *one* chance to contribute to code I maintain and build, but if your stuff doesn't work the first time, you will just not get in. 

I understand that you don't care, but please take that as a lesson for the future. It also reflects badly on you if you put code on the Internet which does not work, especially if you connect your real name to it.

**Comment by romainr** [comment]
No spam allowed, only constructive feedback

**Comment by wwat** [comment]
Are you fucking insane? Do you want me to put my comments in some other public place on the Internet instead?

**Comment by wwat** [comment]
Have

**Comment by wwat** [comment]
Fun

**Comment by wwat** [comment]
Deleting

**Comment by wwat** [comment]
Everything

**Comment by wwat** [comment]
Get

**Comment by wwat** [comment]
A

**Comment by wwat** [comment]
Fucking

**Comment by wwat** [comment]
Brain

**Comment by wwat** [comment]
You

**Comment by wwat** [comment]
Should fucking thank me for my help in identifying your incompetence.
